services:
  api-rest-basic:
    image: api-rest-basic # nombre de la imagen del contenedor
    build: ./  # generaci贸n de la imagen a partir de la configuraci贸n indicada en Dockerfile
    container_name: api-rest-basic
    environment:
      - PORT=3000  # puerto de escucha del contenedor
    ports:
      - "3000:3000"  # redirecci贸n a un puerto del sistema anfitri贸n (izquierda) del puerto de escucha del contenedor (derecha)
